import sys, time
sys.path.insert(0, "/app")
from app.pool import get_pool

TESTES = {}
TESTES["T100"] = """SELECT
    18                          AS CODFILIAL,
    SUM(v.VLATEND)                      AS FATURAMENTO_BRUTO,
    COUNT(DISTINCT v.NUMTRANSVENDA)     AS QTD_NOTAS,
    COUNT(DISTINCT v.CODCLI)            AS QTD_CLIENTES,
    COUNT(DISTINCT v.CODPROD)           AS QTD_SKUS
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
WHERE v.CODFILIAL = '18'
  AND v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1"""
TESTES["T102"] = """SELECT
    SUBSTR(NVL(a.RAMO,'(sem ramo)'),1,30) AS RAMO,
    COUNT(DISTINCT v.CODCLI)              AS QTD_CLIENTES,
    SUM(v.VLATEND)                        AS FATURAMENTO
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCATIVI a ON a.CODATIV = v.CODATIV
WHERE v.CODFILIAL = '18'
  AND v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1
GROUP BY a.RAMO
ORDER BY FATURAMENTO DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T103"] = """SELECT
    v.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,32)  AS RCA,
    SUBSTR(NVL(s.NOME,'-'),1,25)  AS SUPERVISOR,
    SUM(v.VLATEND)                AS REAL,
    COUNT(DISTINCT v.CODCLI)      AS POSITIVACAO,
    COUNT(DISTINCT v.NUMPED)      AS PEDIDOS
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = v.CODUSUR
LEFT JOIN EBD.PCSUPERV s ON s.CODSUPERVISOR = v.CODSUPERVISOR
WHERE v.CODFILIAL = '18'
  AND v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1
GROUP BY v.CODUSUR, u.NOME, s.NOME
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T104"] = """SELECT
    18                                                       AS CODFILIAL,
    COUNT(*)                                                         AS QTD_TITULOS,
    COUNT(DISTINCT p.CODCLI)                                         AS QTD_CLIENTES,
    SUM(p.VALOR)                                                     AS CARTEIRA_ABERTA,
    SUM(CASE WHEN p.DTVENC < TRUNC(SYSDATE) THEN p.VALOR ELSE 0 END) AS VALOR_INAD,
    ROUND(SUM(CASE WHEN p.DTVENC < TRUNC(SYSDATE) THEN p.VALOR ELSE 0 END)
          / NULLIF(SUM(p.VALOR),0) * 100, 2)                         AS PCT_INAD
FROM EBD.PCPREST p
WHERE p.CODFILIAL = '18'
  AND p.DTPAG IS NULL"""
TESTES["T105"] = """WITH venda30 AS (
    SELECT v.CODPROD, SUM(v.QT) AS QT30
    FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
    WHERE v.CODFILIAL = '18'
      AND v.DTSAIDA >= TRUNC(SYSDATE) - 30
      AND v.CONDVENDA = 1
    GROUP BY v.CODPROD
)
SELECT
    e.CODPROD,
    SUBSTR(NVL(p.DESCRICAO,'?'),1,40)                       AS PRODUTO,
    NVL(e.QTESTGER,0) - NVL(e.QTRESERV,0) - NVL(e.QTBLOQUEADA,0) AS ESTOQUE_LIVRE,
    e.CUSTOFIN                                              AS CUSTO_UNIT,
    (NVL(e.QTESTGER,0) - NVL(e.QTRESERV,0) - NVL(e.QTBLOQUEADA,0)) * NVL(e.CUSTOFIN,0) AS VALOR_ESTOQUE,
    ROUND(NVL(e.QTESTGER,0) / NULLIF(NVL(vd.QT30,0)/30, 0), 0) AS DIAS_COBERTURA
FROM EBD.PCEST e
LEFT JOIN EBD.PCPRODUT p ON p.CODPROD = e.CODPROD
LEFT JOIN venda30 vd     ON vd.CODPROD = e.CODPROD
WHERE e.CODFILIAL = '18'
  AND NVL(e.QTESTGER,0) > 0
ORDER BY VALOR_ESTOQUE DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T106"] = """WITH fat AS (
    SELECT v.CODCLI, SUM(v.VLATEND) AS REAL
    FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
    WHERE v.CODFILIAL = '18'
      AND v.DTSAIDA >= TRUNC(SYSDATE,'MM')
      AND v.CONDVENDA = 1
    GROUP BY v.CODCLI
)
SELECT
    CASE WHEN NVL(c.BLOQUEIO,'N') = 'S' THEN 'BLOQUEADO' ELSE 'LIBERADO' END AS SITUACAO,
    COUNT(*)          AS QTD_CLIENTES,
    SUM(NVL(f.REAL,0)) AS FATURAMENTO_MES
FROM EBD.PCCLIENT c
LEFT JOIN fat f ON f.CODCLI = c.CODCLI
WHERE c.CODFILIALNF = '18'
GROUP BY CASE WHEN NVL(c.BLOQUEIO,'N') = 'S' THEN 'BLOQUEADO' ELSE 'LIBERADO' END
ORDER BY QTD_CLIENTES DESC"""
TESTES["T107"] = """SELECT
    v.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,32) AS RCA,
    COUNT(DISTINCT v.CODCLI)     AS POSITIVACAO,
    COUNT(DISTINCT v.NUMPED)     AS PEDIDOS,
    SUM(v.VLATEND)               AS REAL
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = v.CODUSUR
WHERE v.CODFILIAL = '18'
  AND v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1
GROUP BY v.CODUSUR, u.NOME
ORDER BY POSITIVACAO DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T111"] = """SELECT
    pc.NUMPED,
    pc.CODCLI,
    SUBSTR(NVL(c.CLIENTE,'?'),1,35) AS CLIENTE,
    pc.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,30)    AS RCA,
    pc.DATA                         AS DTPEDIDO,
    pc.VLTOTAL
FROM EBD.PCPEDC pc
LEFT JOIN EBD.PCCLIENT c ON c.CODCLI = pc.CODCLI
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = pc.CODUSUR
WHERE pc.CODFILIAL = '18'
  AND pc.POSICAO = 'B'
  AND pc.DTCANCEL IS NULL
  AND pc.DATA >= TRUNC(SYSDATE) - 30
ORDER BY pc.VLTOTAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T113"] = """SELECT
    pc.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,32) AS RCA,
    COUNT(*)                     AS QTD_PEDIDOS,
    SUM(pc.VLTOTAL)              AS VL_PIPELINE
FROM EBD.PCPEDC pc
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = pc.CODUSUR
WHERE pc.CODFILIAL = '18'
  AND pc.POSICAO = 'L'
  AND pc.DTCANCEL IS NULL
GROUP BY pc.CODUSUR, u.NOME
ORDER BY VL_PIPELINE DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T114"] = """SELECT
    pc.CODCLI,
    SUBSTR(NVL(c.CLIENTE,'?'),1,40) AS CLIENTE,
    COUNT(*)                        AS QTD_PEDIDOS,
    SUM(pc.VLTOTAL)                 AS VL_ABERTO
FROM EBD.PCPEDC pc
LEFT JOIN EBD.PCCLIENT c ON c.CODCLI = pc.CODCLI
WHERE pc.CODFILIAL = '18'
  AND pc.POSICAO IN ('L','M','B','P')
  AND pc.DTCANCEL IS NULL
GROUP BY pc.CODCLI, c.CLIENTE
ORDER BY VL_ABERTO DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T174"] = """SELECT
    r.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,32) AS RCA,
    COUNT(*)                     AS CLIENTES_PLANEJADOS
FROM EBD.PCROTACLI r
JOIN EBD.PCUSUARI u ON u.CODUSUR = r.CODUSUR
WHERE u.CODFILIAL = '18'
  AND u.DTTERMINO IS NULL
  AND UPPER(r.DIASEMANA) = UPPER('QUINTA')
GROUP BY r.CODUSUR, u.NOME
ORDER BY CLIENTES_PLANEJADOS DESC"""
TESTES["T180"] = """WITH rota_dia AS (
    SELECT r.CODUSUR, r.CODCLI
    FROM EBD.PCROTACLI r
    JOIN EBD.PCUSUARI u ON u.CODUSUR = r.CODUSUR
    WHERE u.CODFILIAL = '18'
      AND u.DTTERMINO IS NULL
      AND UPPER(r.DIASEMANA) = UPPER('QUINTA')
),
vendeu AS (
    SELECT DISTINCT v.CODUSUR, v.CODCLI
    FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
    WHERE v.CODFILIAL = '18'
      AND v.DTSAIDA >= TRUNC(SYSDATE)
      AND v.CONDVENDA = 1
)
SELECT
    rd.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,32)                                   AS RCA,
    COUNT(*)                                                       AS CLIENTES_ROTA,
    COUNT(vd.CODCLI)                                               AS POSITIVADOS,
    ROUND(COUNT(vd.CODCLI) / NULLIF(COUNT(*),0) * 100, 1)          AS PCT_APROVEITAMENTO
FROM rota_dia rd
LEFT JOIN vendeu vd      ON vd.CODUSUR = rd.CODUSUR AND vd.CODCLI = rd.CODCLI
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = rd.CODUSUR
GROUP BY rd.CODUSUR, u.NOME
ORDER BY PCT_APROVEITAMENTO DESC NULLS LAST"""
TESTES["T192"] = """SELECT
    v.CODPROD,
    SUBSTR(NVL(MAX(v.DESCRICAO),'?'),1,45) AS PRODUTO,
    SUM(v.QT)                              AS QTD,
    SUM(v.VLATEND)                         AS REAL,
    COUNT(DISTINCT v.CODCLI)               AS CLIENTES
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
WHERE v.CODFILIAL = '18'
  AND v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1
GROUP BY v.CODPROD
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T193"] = """SELECT
    SUBSTR(NVL(p.MARCA,'(sem marca)'),1,30) AS MARCA,
    v.CODFILIAL,
    SUM(v.VLATEND)                          AS REAL,
    SUM(v.QT)                               AS QTD
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCPRODUT p ON p.CODPROD = v.CODPROD
WHERE v.DTSAIDA BETWEEN TRUNC(SYSDATE,'MM') AND SYSDATE
  AND v.CONDVENDA = 1
GROUP BY p.MARCA, v.CODFILIAL
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T203"] = """WITH vendas_gc AS (
    SELECT s.CODGERENTE, SUM(v.VLATEND) AS REAL
    FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
    JOIN EBD.PCSUPERV s ON s.CODSUPERVISOR = v.CODSUPERVISOR
    WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
      AND v.CONDVENDA = 1
      AND s.CODGERENTE IS NOT NULL
    GROUP BY s.CODGERENTE
),
meta_gc AS (
    SELECT CODIGO AS CODGERENTE, SUM(VLVENDAPREV) AS META
    FROM EBD.PCMETA
    WHERE TIPOMETA = 'GC' AND TRUNC(DATA,'MM') = TRUNC(SYSDATE,'MM')
    GROUP BY CODIGO
)
SELECT
    vg.CODGERENTE,
    SUBSTR(NVL(g.NOMEGERENTE,'?'),1,35)          AS GERENTE,
    vg.REAL,
    NVL(mg.META,0)                                AS META,
    ROUND(vg.REAL / NULLIF(mg.META,0) * 100, 2)   AS PCT_META
FROM vendas_gc vg
LEFT JOIN EBD.PCGERENTE g ON g.CODGERENTE = vg.CODGERENTE
LEFT JOIN meta_gc mg      ON mg.CODGERENTE = vg.CODGERENTE
ORDER BY vg.REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T205"] = """SELECT
    v.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,35) AS NOME_RCA,
    SUBSTR(NVL(s.NOME,'-'),1,25) AS SUPERVISOR,
    SUM(v.VLATEND)               AS REAL,
    COUNT(DISTINCT v.CODCLI)     AS POSITIVACAO,
    COUNT(DISTINCT v.NUMPED)     AS PEDIDOS
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = v.CODUSUR
LEFT JOIN EBD.PCSUPERV s ON s.CODSUPERVISOR = v.CODSUPERVISOR
WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
  AND v.CONDVENDA = 1
GROUP BY v.CODUSUR, u.NOME, s.NOME
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T207"] = """SELECT
    v.CODCLI,
    SUBSTR(NVL(MAX(v.CLIENTE),'?'),1,40) AS CLIENTE,
    SUBSTR(NVL(MAX(a.RAMO),'-'),1,25)    AS RAMO,
    MAX(v.UF)                            AS UF,
    COUNT(DISTINCT v.NUMTRANSVENDA)      AS QTD_NOTAS,
    COUNT(DISTINCT v.CODFILIAL)          AS QTD_FILIAIS,
    SUM(v.VLATEND)                       AS REAL
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCATIVI a ON a.CODATIV = v.CODATIV
WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
  AND v.CONDVENDA = 1
GROUP BY v.CODCLI
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T208"] = """WITH inad_filial AS (
    SELECT
        p.CODFILIAL,
        COUNT(*)                 AS QTD_TITULOS,
        COUNT(DISTINCT p.CODCLI) AS QTD_CLIENTES,
        SUM(p.VALOR)             AS CARTEIRA_ABERTA,
        SUM(CASE WHEN p.DTVENC < TRUNC(SYSDATE) THEN p.VALOR ELSE 0 END) AS INAD
    FROM EBD.PCPREST p
    WHERE p.DTPAG IS NULL
    GROUP BY p.CODFILIAL
)
SELECT
    ip.CODFILIAL,
    SUBSTR(NVL(pf.FANTASIA,'?'),1,28) AS FILIAL,
    ip.QTD_TITULOS,
    ip.QTD_CLIENTES,
    ip.CARTEIRA_ABERTA,
    ip.INAD,
    ROUND(ip.INAD / NULLIF(ip.CARTEIRA_ABERTA,0) * 100, 2) AS PCT_INAD
FROM inad_filial ip
LEFT JOIN EBD.PCFILIAL pf ON pf.CODIGO = ip.CODFILIAL
ORDER BY ip.INAD DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T209"] = """SELECT
    v.CODPROD,
    SUBSTR(NVL(MAX(v.DESCRICAO),'?'),1,40)   AS PRODUTO,
    SUBSTR(NVL(MAX(v.FORNECPRINC),'?'),1,25) AS FORNECEDOR,
    SUM(v.QT)                                AS QTD,
    SUM(v.VLATEND)                           AS REAL,
    COUNT(DISTINCT v.CODFILIAL)              AS QTD_FILIAIS,
    COUNT(DISTINCT v.CODCLI)                 AS QTD_CLIENTES
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
  AND v.CONDVENDA = 1
GROUP BY v.CODPROD
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T212"] = """SELECT
    pc.NUMPED,
    pc.CODFILIAL,
    pc.CODCLI,
    SUBSTR(NVL(c.CLIENTE,'?'),1,35) AS CLIENTE,
    pc.CODUSUR,
    SUBSTR(NVL(u.NOME,'?'),1,30)    AS RCA,
    pc.DATA                         AS DTPEDIDO,
    pc.POSICAO,
    pc.VLTOTAL
FROM EBD.PCPEDC pc
LEFT JOIN EBD.PCCLIENT c ON c.CODCLI = pc.CODCLI
LEFT JOIN EBD.PCUSUARI u ON u.CODUSUR = pc.CODUSUR
WHERE pc.POSICAO IN ('B','P')
  AND pc.DTCANCEL IS NULL
  AND pc.DATA >= TRUNC(SYSDATE) - 30
ORDER BY pc.VLTOTAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T241"] = """SELECT
    s.CODGERENTE,
    SUBSTR(NVL(g.NOMEGERENTE,'?'),1,35) AS GERENTE,
    SUM(v.VLATEND)                      AS REAL,
    COUNT(DISTINCT v.CODUSUR)           AS QTD_RCAS,
    COUNT(DISTINCT v.CODCLI)            AS POSITIVACAO
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
JOIN EBD.PCSUPERV s      ON s.CODSUPERVISOR = v.CODSUPERVISOR
LEFT JOIN EBD.PCGERENTE g ON g.CODGERENTE = s.CODGERENTE
WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
  AND v.CONDVENDA = 1
  AND s.CODGERENTE IS NOT NULL
GROUP BY s.CODGERENTE, g.NOMEGERENTE
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""
TESTES["T242"] = """SELECT
    v.CODSUPERVISOR,
    SUBSTR(NVL(s.NOME,'?'),1,32) AS SUPERVISOR,
    SUM(v.VLATEND)               AS REAL,
    COUNT(DISTINCT v.CODUSUR)    AS QTD_RCAS,
    COUNT(DISTINCT v.CODCLI)     AS POSITIVACAO
FROM EBD.VIEW_VENDAS_RESUMO_FATURAMENTO v
LEFT JOIN EBD.PCSUPERV s ON s.CODSUPERVISOR = v.CODSUPERVISOR
WHERE v.DTSAIDA >= TRUNC(SYSDATE,'MM')
  AND v.CONDVENDA = 1
GROUP BY v.CODSUPERVISOR, s.NOME
ORDER BY REAL DESC NULLS LAST
FETCH FIRST 10 ROWS ONLY"""

p = get_pool(); c = p.acquire()
ok = ruim = 0
try:
    for tid in sorted(TESTES):
        t0 = time.perf_counter()
        try:
            cur = c.cursor(); cur.execute(TESTES[tid]); n = len(cur.fetchall())
            dt = time.perf_counter() - t0
            flag = "  <<< LENTO" if dt > 20 else ""
            print(f"  {tid:6s} OK   {n:5d} linhas {dt:7.1f}s{flag}"); ok += 1
        except Exception as e:
            print(f"  {tid:6s} ERRO {str(e)[:78]}"); ruim += 1
finally:
    p.release(c)
print(f"\n{'='*60}\nOK: {ok}   ERRO: {ruim}\n{'='*60}")
sys.exit(1 if ruim else 0)